language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
addons:
  chrome: beta
before_install:
  - npm install -g npm@latest
  - "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &"
script:
  - npm test

