language: node_js
node_js:
  - 8
cache:
  yarn: true
  directories:
    - ~/.npm
    - node_modules
addons:
  chrome: beta
before_install:
  - "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &"
install:
  - yarn
before_script:
  - yarn start -- --silent &
script:
  - yarn test

