language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
addons:
  chrome: beta
before_install:
  - "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  before_script:
  - npm start
script:
  - npm run test


